# -*- coding: utf-8 -*-
"""is.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOz_hjvMWpvNrpZkw2Ti_K8tSK6P0Qam
"""

!pip -q install pycryptodome
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad, unpad

plaintext = input("Enter the message to encrypt: ")
# Convert plaintext into bytes
data = plaintext.encode('utf-8')

# Step 2: Generate a 128-bit (16-byte) AES secret key
key = get_random_bytes(16)

cipher = AES.new(key, AES.MODE_CBC)
# Save the Initialization Vector (IV)
iv = cipher.iv
ciphertext = cipher.encrypt(pad(data, AES.block_size))

print("\n========== Encryption ==========")
print("Original Plaintext :", plaintext)
print("Secret Key (Hex) :", key.hex())
print("Initialization IV :", iv.hex())
print("Cipher Text (Hex) :", ciphertext.hex())

decrypt_cipher = AES.new(key, AES.MODE_CBC, iv)

decrypted_data = unpad(
 decrypt_cipher.decrypt(ciphertext),
 AES.block_size
)
decrypted_text = decrypted_data.decode('utf-8')

print("\n========== Decryption ==========")
print("Decrypted Text :", decrypted_text)

if plaintext == decrypted_text:
 print("\nResult: Encryption and Decryption Successful.")
else:
 print("\nResult: Encryption and Decryption Failed.")