# -*- coding: utf-8 -*-
"""Copy of is-prectical1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a1bfRIa8QNl2YfXVCCUy0hqMjgUApua
"""

import socket
import platform
import requests
from datetime import datetime

print("=" * 70)
print("CYBERSECURITY ENVIRONMENT SETUP USING GOOGLE COLAB")
print("=" * 70)

print("\nCURRENT DATE AND TIME")
print("-" * 70)
current_time = datetime.now()
print("Current Date and Time :", current_time)

print("\nSYSTEM INFORMATION")
print("-" * 70)
print("Operating System :", platform.system())
print("System Release :", platform.release())
print("System Version :", platform.version())
print("Machine Type :", platform.machine())
print("Processor :", platform.processor())

print("\nHOST INFORMATION")
print("-" * 70)
hostname = socket.gethostname()
print("Hostname :", hostname)
try:
 ip_address = socket.gethostbyname(hostname)
 print("IP Address :", ip_address)
except:
 print("Unable to Retrieve IP Address")

print("\nINTERNET CONNECTIVITY TEST")
print("-" * 70)
try:
 response = requests.get("https://github.com/")
 print("Connection Status : SUCCESS")
 print("HTTP Status Code :", response.status_code)
except:
 print("Connection Status : FAILED")

print("\nDNS RESOLUTION TEST")
print("-" * 70)
try:
 GitHub_ip = socket.gethostbyname("www.github.com")
 print("Domain Name : www.github.com")
 print("Resolved IP :", GitHub_ip)
except:
 print("DNS Resolution Failed")

print("\nPORT CONNECTIVITY TEST")
print("-" * 70)
host = "google.com"
ports = [80, 443]
for port in ports:
  try:
    connection = socket.create_connection((host, port), timeout=5)
    print(f"Port {port} : OPEN")
    connection.close()
  except:
         print(f"Port {port} : CLOSED")

print("\nWEBSITE SECURITY CHECK")
print("-" * 70)
url = "https://www.google.com"
if url.startswith("https://"):
 print("Secure HTTPS Protocol Detected")
else:
 print("Insecure Protocol")

print("\nCYBERSECURITY ENVIRONMENT STATUS")
print("-" * 70)
print("✓ Python Environment Ready")
print("✓ Internet Connectivity Verified")
print("✓ DNS Resolution Working")
print("✓ Port Connectivity Verified")
print("✓ HTTPS Security Verified")
print("✓ Security Environment Ready")
print("\nPractical Completed Successfully")
print("=" * 70)